channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.10
  - boa
  - ipython
  - lazy_loader >=0.4
  - matplotlib-base >=3
  - mypy
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-build
  - python-gmsh >=4
  - ruff
  - scons >=4.6
  - setuptools >=77
  - setuptools_scm >=8
  - sphinx >=7.1
  - sphinx-argparse
  - sphinx-book-theme
  - sphinx-copybutton >=0.5.1
  - sphinx-design
  - sphinxcontrib-bibtex
  - twine
  - waves >=0.13
