channels:
  - conda-forge

dependencies:
  - black
  - boa
  - flake8
  - ipython
  - lazy_loader >=0.4
  - mypy
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-build
  - python-gmsh >=4
  - scons >=4.6
  - setuptools >=77
  - setuptools_scm >=8
  - sphinx >=5.1
  - sphinx-argparse
  - sphinx-book-theme
  - sphinx-copybutton >=0.5.1
  - sphinxcontrib-bibtex
  - twine
  - waves >=0.13
